spring.application.name=demo

server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/ticket_engine_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=rafeeq123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Redis Connection Settings
spring.data.redis.host=localhost
spring.data.redis.port=6379